{% set name = "openlineage-python" %}
{% set version = "0.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage_python-{{ version }}.tar.gz
  sha256: b7b5a7300eb342d96eb1364e7080e69ad7be693fdf2ac9c1fd473eeb521517db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.15
    - pip
  run:
    - python >=3.7
    - attrs >=23.1
    - python-dateutil >=2.8.2
    - pyyaml >=6
    - requests >=2.24.0

test:
  imports:
    - openlineage.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
